module.exports = {
	'colors' : {
		'valhalla' : '#282A40',
		'meadow' : '#11B1A9',
		'bittersweet' : '#FA7555',
		'spindle' : '#BCE5EE',
		'purple' : '#6667AB',
		'vine': '#c23854',
		'greylighter' : '#F4F4F8',
		'tertiary': '#FA7555',
		// n00bs colors - my account
		'greylight':'#F5F8FD',
		'greendark':'#08534B',
		'greenmiddle':' #39988D',
		'greenlight':'#ABE8E1',
		'greenlight2':'#E8F3F2',
		'greenlight3':'#E1EFEE',
		'greenlighter':'#F3F9F8',
		'yellowdark':'#FFEEB7',
		'yellowlight':'#FFFCA8',
		'orangedark':'#F7AE56',
		'orangelight':'#FFFAF0',
		'reddark':'#D9531F',
		'redlight':'#D97346',
		// n00bs colors - product reader
		'salmon':'#F87C56',
		'turquoise':'#59C3D1',
		'greylight2':'#DCE7EE',
		'greenlight4':'#E7F7F6',
		'greylight3':'#B3CADB'
	},
	'spacing': '1rem',
	'primary': 'colors(valhalla)',
	'secondary': 'colors(meadow)',
	'tertiary': 'colors(bittersweet)',
	'radius': '15px',

	'body': {
		'background': '#FCFCFC',
		'block-background': 'colors(white)',
		'font-color': 'primary',
		'font-size'		: '24px',
		'font-size-lg'	: '22px',
		'font-size-md'	: '20px',
		'font-size-sm'	: '18px',
		'font-size-xxs'	: '16px',
		'line-height' 	: '1.45',
	},
	'header': {
		'background': 'colors(none)',
		// 'font-color': 'body(font-color)',
		'font-size': '0.8em',
	},
	'footer': {
		'background': 'primary',
		'font-color': 'colors(white)',
		'font-size': '0.8em',
	},
	'link': {
		'font-color': 'body(font-color)',
		'font-color-hover': 'secondary',
		'font-color-focus': 'secondary',
		'underline': true,
		'underline-on-hover': true,
	},
	'btn':{
		'background': 'primary',
		'font-color': 'contrastFW(colors(white),primary)',
		'border-size': '2px',
		'radius': false,
		'uppercase': false,
		'font-weight': 400,
	},
	// 'input-invalid': {
	// 	'border-color': 'input(border-color)',
	// },
	'thumb-color': 'input(background)',
	'thumb-width': '0.5em',
};
